### ISSUE TITLE
Repetitive words count/ French not scoring correctly

### ISSUE THREAD

**Issue by julianoventola** [akashlilhare/dart_sentiment#1]
- Even when a positivo word is repeatedly found, it counts, i don't know if this is correct. 

- Not scoring positive words for French ( did not test other languages to check if they have the same problem)
![image](https://user-images.githubusercontent.com/28475558/141322802-9f7751dd-c9ec-420a-b4fe-b75dbe0134bd.png)

**Comment by akashlilhare** [comment]
I hope the fix will work for you.
